name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:        # <--- Este é o equivalente ao "Stage: build"
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Simulando o Build
          run: echo "Compilando a aplicação..."
  test-job:            
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "This job tests something"

  test-job2:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install flask
        run: pip install flask

      - name: run tests
        run: python -m unittest -v tests/appTest.py
      
      - name: Install coverage
        run: pip install coverage

      - name: Run tests with coverage
        run: |
          python -m coverage run -m unittest -v tests/appTest.py 
          python -m coverage report 


      

